### ISSUE TITLE
docker部署失败

### ISSUE THREAD

**Issue by shiqianwei0508** [Anduin2017/HowToCook#1337]
### 环境
- docker version: 19.03.8
- docker-compose version: 1.25.0

### docker-compose.yml
```yml
version: "3"
services:
  HowToCook:
    container_name: HowToCook
    image: ghcr.io/anduin2017/how-to-cook:latest
    ports:
      - "15000:5000"
    restart: unless-stopped
```

### 启动日志
```
Attaching to HowToCook
HowToCook    | Failed to create CoreCLR, HRESULT: 0x80070008
HowToCook    | Failed to create CoreCLR, HRESULT: 0x80070008
HowToCook    | Failed to create CoreCLR, HRESULT: 0x80070008
HowToCook    | Failed to create CoreCLR, HRESULT: 0x80070008
HowToCook    | Failed to create CoreCLR, HRESULT: 0x80070008
```
